---
title: "Untitled"
output: html_document
date: '2022-11-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(purrr)
library(dplyr)
library(tidyverse)
library(urbnmapr)
library(urbnthemes)
library(plotly)
library(trelliscopejs)
library(reshape2)
library(tibble)
library(dplyr)
library(tidyr)
library(colourvalues)
library(patchwork)
library(randomForest)
library(data.table)
```

## load csvs
```{r}

regions <- unique(read.csv("regional_designation.csv"))
HO_data <- unique(read.csv("haf_data_all_counties_update.csv"))
pop_density <- read.csv("Average_Household_Size_and_Population_Density_-_County.csv")
# response_data <- read.csv("Perc_diff_HO_RACE_by_County.csv")
importances_final <- read.csv("importances_final.csv", check.names = F)[-1]
random_forest_models <-  readRDS("Main_effects_RF.RDS")

var_desc <- read.csv("Variable_Descriptions.csv")


finalM <- read.csv("final_model_df.csv")[-1]
finalM <- finalM[!apply(is.na(finalM), 1, any),]


table(finalM[finalM$Race_pop > 500, c("RACE")])

```

## Figure 1 - Maps
```{r}

## observed across all models 

keeps <- unique(finalM$county_fips)
cntys <- get_urbn_map("counties", sf = TRUE)
cntys$observed <- "Not observed" 

cntys$observed[as.numeric(cntys$county_fips) %in% keeps] <- "Observed"

obs_plot <- ggplot() +
      geom_sf(cntys,
              mapping = aes(fill = observed),
              color = "#ffffff", size = 0.25) +
      labs(fill = "") + theme_bw()
obs_plot
## Region designations
region_join <- left_join(get_urbn_map("states", sf = TRUE), regions, by = c("state_name" = "State"))

 region_plot <- ggplot() +
   scale_fill_brewer(palette = "Spectral") +
      geom_sf(region_join,
              mapping = aes(fill = Division),
              color = "#ffffff", size = 0.25) +
      labs(fill = "") + theme_bw()
 region_plot

## Join w/ other datasets
cntys$county_fips <- as.numeric(cntys$county_fips)

## Homeownership - foreclosure
HO_join <-  left_join(cntys, HO_data, by = c("state_name" = "st", "county_name" = "county"))

 HO_plot <- ggplot() +
      geom_sf(HO_join,
              mapping = aes(fill = log(predicted_foreclosure_rate)),
              color = "#ffffff", size = 0.25) +
      labs(fill = "log(foreclosure rate)") + theme_bw()  + 
   scale_fill_continuous(type = "viridis")
HO_plot
## Population density
pd_join <-  left_join(cntys, pop_density, by = c("county_fips" = "GEOID"))


pop_density_plot <- ggplot() +
  geom_sf(pd_join,
          mapping = aes(fill = log(B01001_calc_PopDensity)),
          color = "#ffffff", size = 0.25) +
  labs(fill = "log(population density)") + theme_bw()  + 
scale_fill_continuous(type = "viridis")

pop_density_plot

```

```{r, warning=F}

pdf("maps.pdf", width = 20, height = 10)
suppressMessages(
  suppressWarnings(wrap_plots(region_plot + theme(text = element_text(size = 15)), 
                      obs_plot + theme(text = element_text(size = 15)), 
                      pop_density_plot+ theme(text = element_text(size = 15)),
                      HO_plot+ theme(text = element_text(size = 15)), 
                      nrow = 2) + patchwork::plot_annotation(tag_levels = "A")))

dev.off()

```

## Correlation heatmap

```{r}

d <- finalM[c(12:78, 81)] ## numeric predictors only
d <- d[colnames(d) != "Race_employment"]

## Remane columns as needed
col_names <- as.list(colnames(d))
names(col_names) <- colnames(d)
for(colnm in colnames(d)){
  var_replace <- var_desc$Simplified_Variable_Name[var_desc$Variable.Name == colnm]
  if(length(var_replace) > 0) col_names[[colnm]] <- var_replace
}
colnames(d) <- as.character(col_names)

d2 <- d %>% 
  as.matrix %>%
  cor(method = "spearman") %>%
  as.data.frame %>%
  rownames_to_column(var = 'var1') %>%
  gather(var2, value, -var1)

cors <- d %>%
  as.matrix %>%
  cor(method = "spearman")

hclust_res <- hclust(dist(cors))

## remove Race employment -- accounted for in other variables
d2$var1 <- factor(d2$var1, colnames(cors)[hclust_res$order])
d2$var2 <- factor(d2$var2, colnames(cors)[hclust_res$order])

d2 <- d2[!is.na(d2$var1),]
d2 <- d2[!is.na(d2$var2),]

pdf("cor.pdf", width = 10, height = 9)
ggplot(d2, aes( x = var1, y = var2, fill = value)) + geom_tile() + theme_bw() + 
  theme(axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.5)) + 
  labs(x = "", y = "", fill = "Correlation") + 
  scale_fill_gradient2()
dev.off()

```

## Timeline graphic

```{r}

labs <- c("Building Permits", "Census Population Estimates",
            "Census Population Change Estimates",
            "DOD Per Diem Rates", "High School",
            "Secondary Education", "Homeownership Demographics",
            "Household Conditions", "Job Availability",
            "Poverty Demographics", "Unequal Commute Times")

yr_st <- c(2015, 2015, 2015, 2015, 2016, 2015, 2015, 2015, 2015, 2017, 2014)
yr_ed <- c(2019, 2019, 2019, 2019, 2019, 2017, 2019, 2018, 2018, 2017, 2018)

status <- c("Removed", "Kept", "Kept", "Kept", "Kept", "Removed",
             "Kept", "Removed", "Kept", "Removed", "Kept")

length(status)

TimeData <- data.table(
  Dataset = 1:11,
  YearStart = yr_st,
  YearEnd = yr_ed,
  Status = status,
  Label = labs
) %>%
  filter(Status == "Kept") %>%
  mutate(YearCenter = (YearStart + YearEnd) / 2) %>%
  mutate(Dataset = 1:7)

pdf("Timeline_Graphic.pdf", width = 8, height = 4)

thePlot <- ggplot(TimeData, aes(x = YearStart, xend = YearEnd, y = Dataset, yend = Dataset, label = Label)) +
  geom_vline(xintercept = c(2015, 2019), color = "red") +
  geom_segment() + geom_label(x = TimeData$YearCenter) + ylab("") + theme_minimal() + xlab("Years") +
  theme(axis.text.y = element_blank()) + xlim(c(2014, 2020)) +
  guides(fill=guide_legend(title="Status", override.aes = aes(label = ""))) 
thePlot

dev.off()

# ggsave("Timeline_Graphic.png", path = "~/Downloads", width = 8, height = 4, units = "in")


### Capitalize dataset names

```


## Figure 2 County homeownership equity


```{r}

dat <- unique(finalM)
# dat <- unique(response_data)
dat$HO_share <-  dat$HO_share*100
dat$Race_frac <-  dat$Race_frac*100

dat <- dat[!is.na(dat$HO_share),]
dat <- dat[!is.na(dat$Race_frac),]

dat <- dat[dat$RACE != "Other",]

pdf("HO.pdf", width = 9, height = 6)
ggplot(dat, 
     mapping = aes(y = HO_share, x = Race_frac)) + 
  geom_hex(aes(fill = stat(log(count)))) +
# geom_hex() +
facet_wrap(vars(RACE), nrow = 2) +
geom_segment(x = 0, y = 0, xend = 100, yend = 100, 
             inherit.aes = F, color = "red", alpha = 0.5, linetype=2) +
scale_x_continuous(limits = c(0,100)) +
scale_y_continuous(limits = c(0,100)) +
labs(y = paste("% homeowners"), 
     x = paste("% in population ( Age > 19 )"),
     title = "County Homeownership Equity") +
  scale_fill_continuous("Log( N Counties )") + theme_bw() +
  theme(text = element_text(size = 15))
dev.off()

# Seeing weird banding patterns? Check your package, 3.4.0 appears to have an error
# packageurl <- "https://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_3.3.6.tar.gz"
# install.packages(packageurl, repos=NULL, type="source")
# library(ggplot2)
# 

## Sanity check
# df <- data.frame(
#   x = rnorm(10000),
#   y = rnorm(10000)
# )
# 
# plot.df <- ggplot(data = df, aes(x = x, y = y)) +
#   geom_hex(aes(fill = stat(count)))
# print(plot.df)

```


## Variable Importance

## Figure 3 importance boxplots (top 20)
```{r}

## each data

## good models only
importance_good <- importances_final[importances_final$Validation_rsq > 0.1,]

## Best features by top 5% quantile of %IncMSE
top_20s <- importance_good %>% group_by(Holdout_Division, Race) %>%
  summarise(
    Feature = Feature[`%IncMSE` > quantile(`%IncMSE`, .95)],
    top_incmse = `%IncMSE`[`%IncMSE` > quantile(`%IncMSE`, .95)],
    NP = IncNodePurity[`%IncMSE` > quantile(`%IncMSE`, .95)],
    rsq = Validation_rsq[`%IncMSE` > quantile(`%IncMSE`, .95)],
    mse_val = Validation_mse[`%IncMSE` > quantile(`%IncMSE`, .95)],
    mse_test = Test_mse[`%IncMSE` > quantile(`%IncMSE`, .95)]
  )

```

```{r}

top_20s_sub <- top_20s

for(row in 1:nrow(var_desc)){
  var_search <- var_desc[row, "Variable.Name"]
  var_replace <- var_desc[row, "Simplified_Variable_Name"]
  top_20s_sub$Feature <- str_replace_all(top_20s_sub$Feature, var_search, var_replace)
}


top_imp_plots <- map(unique(top_20s_sub$Race), function(race){
  
  df <-  top_20s_sub[top_20s_sub$Race == race,]
  
  med_mse <- df %>% group_by(Feature) %>% summarise(med_incmse = median(top_incmse))
  
  leveler <- arrange(med_mse, desc(med_incmse))$Feature
  
  df$Feature <- factor(df$Feature, levels = leveler)
  
  p <- ggplot(df, 
         aes(y = Feature, x = top_incmse)) + 
  geom_boxplot(show.legend = F) + theme_bw() + 
    geom_point(aes(color = Holdout_Division), show.legend = race == "Asian") + labs(col = "Holdout")
  p + labs(y = "", x = "% Increase in MSE",
           title = paste0(race, " models")) + ggplot2::scale_color_discrete()
  
})

names(top_imp_plots) <- c("A", "B", "C", "D")

fig6 = patchwork::wrap_plots(top_imp_plots, guides = "collect") + patchwork::plot_annotation(tag_levels = 'A')

pdf("importance.pdf", width = 9, height = 6)
fig6
dev.off()

# ggsave("fig6.png",plot = fig6,dpi = 300,width = 9,height = 6)
```

## Figure 4 marginal effects
```{r}


div <- "Pacific"
finalM2 <- finalM[finalM$Race_pop > 500,]
finalM2 <- finalM2[!apply(is.na(finalM2), 1, any),]
finalM2 <- finalM2[finalM2$Division != div,]

pdf("mar_eff.pdf", width = 6, height = 6)
par(mfrow = c(2, 2))
for(race in unique(finalM2$RACE)){
  rf <- random_forest_models[[race]][[div]]
  
  finalM_train <-  finalM2[finalM2$RACE == race,]
  finalM_train <- finalM_train[which(colnames(finalM_train) %in% row.names(rf$importance))]
  
  partialPlot(rf, finalM2, "Less.than.high.school", 
              xlab = "jobLessHS",
            ylab = "Marginal effect on response", main = race)
  
}
dev.off()

```


## Trelliscope of hexplots

```{r}

imp_cols <- finalM[colnames(finalM) %in% top_20s$Feature]

# non numeric
imp_cols2 <- imp_cols[!apply(is.na(apply(imp_cols, 2, as.numeric)), 2, any)]

imp_cols_plotter <- cbind(finalM[c("HO_over_Race", "RACE")], imp_cols2) 

# No division for hexplots
 
imp_cols_plotter2 <- melt(imp_cols_plotter, id.vars = c("HO_over_Race", "RACE"), variable.name = "Predictor")

nest_imp_plotter <- imp_cols_plotter2 %>% group_by(Predictor) %>% nest()
plot_hex <- function(pred){
  df <- nest_imp_plotter$data[[which(nest_imp_plotter$Predictor == pred)]]
  ggplot(df, 
     mapping = aes(y = HO_over_Race - 1, x = value)) + 
    geom_hex(aes(fill = stat(log(count)))) +
  facet_wrap(vars(RACE), nrow = 2) +
    geom_hline(yintercept = 0, color = "red", alpha = 0.5, linetype=2) +
  labs(y = paste("Distance from equity"),
       x = pred,
       title = "") +
    scale_fill_continuous("Log( N Counties )") + theme_bw() +
    theme(text = element_text(size = 10))
}

trell_df <- mutate(ungroup(nest_imp_plotter), 
       panel = map_plot(nest_imp_plotter$Predictor, plot_hex))

trelliscope(trell_df, name = "Hex_plots_Eq_dist", path = "./Trelliscope_eq")

```


```{r}

rf_models <- readRDS("Main_effects_RF.RDS")
divs <- unique(finalM$Division)

# nest the data by race
nested_fm <- finalM %>% group_by(RACE) %>% nest()

# set.seed
set.seed(2023)
nested_fm <- nested_fm %>%
  dplyr::mutate(
    # determine hold out set (10% from each county for each race model with populations above 500)
    holdout_data = map(data,function(dat){
      subdata = dat
      # filter to counties greater than 500
      subdata <- subdata[subdata$Race_pop > 500, ]
      # subset 10% from each county
      holdout_subdata <- subdata %>%
        dplyr::group_by(Division) %>%
        sample_frac(0.1) %>% ungroup()
      }),
    # determine the rest of the data (accounting for populations above 500)
    rest_data = map2(data, holdout_data,function(dat,hold_dat){
      subdata = dat
      # filter to counties greater than 500
      subdata <- subdata[subdata$Race_pop > 500, ]
      rest_dat = subdata %>%
        dplyr::filter(!county_fips %in% hold_dat$county_fips)
      })
    )

# find mse for testing of the models
mse_df <- crossing(Race = rep(names(rf_models),9),
                  Holdout_Division = rep(divs,4)) %>%
  data.frame()
mse_df$Test_mse <- NA
for(i in 1:length(rf_models)){
  for(j in 1:length(rf_models[[i]])){
    race_name = names(rf_models)[i]
    division_name = names(rf_models[[i]])[j]
    
    mse_row = which(mse_df$Race == race_name & mse_df$Holdout_Division == division_name)
    predrf = predict(rf_models[[i]][[j]],nested_fm$holdout_data[[i]])

    mse_value = mean((nested_fm$holdout_data[[i]]$HO_over_Race - predrf)^2)
    mse_df[mse_row,]$Test_mse = mse_value

  }
}

pdf("mse_test.pdf", width = 4, height = 4)
ggplot(mse_df, aes(x = Holdout_Division, y = Test_mse)) + geom_point() + 
  facet_wrap(~Race#, scales = "free_y"
             ) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  labs(x = "", y = "Mean square error")
dev.off()

```


```{r}
importances_final <- map_dfr(names(rf_models), function(race){
  
 set_race  <- rf_models[[which(names(rf_models) == race)]]
  
  race_df <- map_dfr(names(set_race), function(div){
    
    set_rf  <- set_race[[which(names(set_race) == div)]]
    df <- as.data.frame(importance(set_rf))
    df$Feature <- row.names(df)
    row.names(df) <- NULL
    df$Holdout_Division <- div
    df$Validation_rsq <- set_rf$test$rsq[length(set_rf$test$rsq)]
    df$Validation_mse <- set_rf$test$mse[length(set_rf$test$mse)]
    df
    
  })
  
  race_df$Race <- race
  race_df
  
})

importances_final <- left_join(importances_final, mse_df)

pdf("val_rsq.pdf", width = 5, height = 5)

unique(importances_final[c("Holdout_Division", "Validation_rsq", "Race")]) %>%
  ggplot(aes(x = Holdout_Division, y = Validation_rsq)) +
  geom_point() + 
  theme_bw() +
  facet_wrap(~Race) + 
  labs(y = "Validation Psuedo R^2", x = "") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

dev.off()

# model_df %>%
#   ggplot(aes(x = Division, y = mse_all)) +
#   geom_point() + 
#   theme_bw() +
#   facet_wrap(~Race) + 
#   labs(y = "Test MSE") +
#   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

```

## Additional White model exploration
```{r}

ggplot(finalM[finalM$RACE == "White",], aes(x = HO_over_Race, y = Race_frac,
                       color = White)) + facet_wrap(~Division) +
  geom_point() + theme_bw() + ggplot2::scale_color_continuous(type = "viridis")

```

```{r}
importances_final <- read.csv("importances_final.csv", check.names = F)[-1]

## each data

## good models only
importance_good <- importances_final[importances_final$Validation_rsq > 0.1,]

## Best features by top 5% quantile of %IncMSE
top_20s <- importance_good %>% group_by(Holdout_Division, Race) %>%
  summarise(
    Feature = Feature[`%IncMSE` > quantile(`%IncMSE`, .95)],
    top_incmse = `%IncMSE`[`%IncMSE` > quantile(`%IncMSE`, .95)],
    NP = IncNodePurity[`%IncMSE` > quantile(`%IncMSE`, .95)],
    rsq = Validation_rsq[`%IncMSE` > quantile(`%IncMSE`, .95)],
    mse_val = Validation_mse[`%IncMSE` > quantile(`%IncMSE`, .95)],
    mse_test = Test_mse[`%IncMSE` > quantile(`%IncMSE`, .95)]
  )

## Frequency of variable labeled as important
top_20_feature_freq <- as.data.frame(table(top_20s[c("Race", "Feature")]))
top_20_feature_freq <- top_20_feature_freq[top_20_feature_freq$Freq > 0,]

## occurance of variables as compared to number of well-performing models
totes_race <- map_dbl(as.character(top_20_feature_freq$Race), function(x){
  switch(x, Asian = 8, Black = 9, Hispanic = 4, White = 8)
})

top_imp_plots <- map(unique(top_20s$Race), function(race){
  
  df <-  top_20s[top_20s$Race == race,]
  
  med_mse <- df %>% group_by(Feature) %>% summarise(med_incmse = median(top_incmse))
  
  leveler <- arrange(med_mse, desc(med_incmse))$Feature
  
  df$Feature <- factor(df$Feature, levels = leveler)
  
  p <- ggplot(df, 
         aes(y = Feature, x = top_incmse)) + 
  geom_boxplot(show.legend = F) + theme_bw() + 
    geom_point(aes(color = Holdout_Division)#, show.legend = race == "Asian"
               ) 
  
  p + labs(y = "", x = "% Increase in MSE",
           title = paste0(race, " models")) +  
    ggplot2::scale_color_discrete() + theme_bw()
  
})

white_all_county <- top_imp_plots[[3]]

######

importances_final <- read.csv("importances_final_white_exc.csv", check.names = F)[-1]

## each data

## good models only
importance_good <- importances_final[importances_final$Validation_rsq > 0.1,]

## Best features by top 5% quantile of %IncMSE
top_20s <- importance_good %>% group_by(Holdout_Division, Race) %>%
  summarise(
    Feature = Feature[`%IncMSE` > quantile(`%IncMSE`, .95)],
    top_incmse = `%IncMSE`[`%IncMSE` > quantile(`%IncMSE`, .95)],
    NP = IncNodePurity[`%IncMSE` > quantile(`%IncMSE`, .95)],
    rsq = Validation_rsq[`%IncMSE` > quantile(`%IncMSE`, .95)],
    mse_val = Validation_mse[`%IncMSE` > quantile(`%IncMSE`, .95)],
    mse_test = Test_mse[`%IncMSE` > quantile(`%IncMSE`, .95)]
  )

top_imp_plots <- map(unique(top_20s$Race), function(race){
  
  df <-  top_20s[top_20s$Race == race,]
  
  med_mse <- df %>% group_by(Feature) %>% summarise(med_incmse = median(top_incmse))
  
  leveler <- arrange(med_mse, desc(med_incmse))$Feature
  
  df$Feature <- factor(df$Feature, levels = leveler)
  
  p <- ggplot(df, 
         aes(y = Feature, x = top_incmse)) + 
  geom_boxplot(show.legend = F) + theme_bw() + 
    geom_point(aes(color = Holdout_Division)#, show.legend = race == "Asian"
               ) 
  
  p + labs(y = "", x = "% Increase in MSE",
           title = paste0(race, " models")) +  
    ggplot2::scale_color_discrete() + theme_bw()
  
})

white_outlier_remove <- top_imp_plots[[3]]

pdf("white_comp.pdf", width = 7, height = 8)
patchwork::wrap_plots(white_all_county + 
                        labs(title = "All counties - White models", color = "", x = "") +
                        lims(x = c(22, 37)) + theme(axis.text.x = element_blank()),
                      white_outlier_remove + 
                        labs(title = "Outliers removed - White models", color = "") +
                        lims(x = c(22, 37)), 
                      nrow = 2,
                      guides = "collect") + patchwork::plot_annotation(tag_levels = 'A')
dev.off()

```




